# Generated by Django 2.0.7 on 2018-09-12 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='owner',
        ),
    ]
