# Generated by Django 2.0.7 on 2018-09-12 16:04

from django.db import migrations, models
import django.db.models.deletion
import rescape_region.models.region


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='boundary',
            field=models.ForeignKey(default=rescape_region.models.region.default_geometry, on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='rescape_region.Feature'),
        ),
    ]
