# Generated by Django 2.0.7 on 2019-01-17 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0002_location_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='rescape_region.Region'),
        ),
    ]
