# Generated by Django 2.0.7 on 2018-09-12 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0002_auto_20180912_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='owner',
        ),
    ]
