# Generated by Django 2.0.7 on 2019-02-04 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0003_project_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
