# Generated by Django 2.0.7 on 2018-09-14 09:36

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import rescape_region.models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0003_groupstate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupstate',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=rescape_region.model_helpers.group_state_default),
        ),
        migrations.AlterField(
            model_name='groupstate',
            name='group',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='auth.Group'),
        ),
    ]
