# Generated by Django 2.0.7 on 2018-09-16 14:20

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion
import rescape_region.model_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0004_auto_20180914_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureCollection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, null=True)),
                ('description', models.CharField(max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('geometry', django.contrib.gis.db.models.fields.GeometryCollectionField(default=rescape_region.model_helpers.feature_collection_geometry_default, srid=4326)),
            ],
        ),
        migrations.AlterField(
            model_name='region',
            name='boundary',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='regions', to='rescape_region.FeatureCollection'),
        ),
    ]
