# Generated by Django 2.0.7 on 2019-02-19 14:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import rescape_region.model_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0004_auto_20190204_1423'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=rescape_region.model_helpers.project_data_default),
        ),
        migrations.AlterField(
            model_name='project',
            name='region',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='rescape_region.Region'),
        ),
    ]
