# Generated by Django 2.0.7 on 2018-09-21 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0005_auto_20180916_1420'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurecollection',
            old_name='geometry',
            new_name='geometry_collection',
        ),
    ]
