# Generated by Django 2.0.7 on 2019-06-06 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0006_settings'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Location',
            new_name='RegionLocation',
        ),
    ]
