# Generated by Django 2.0.7 on 2018-09-21 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0006_auto_20180921_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feature',
            old_name='geometry',
            new_name='geo',
        ),
        migrations.RenameField(
            model_name='featurecollection',
            old_name='geometry_collection',
            new_name='geo_collection',
        ),
    ]
