# Generated by Django 2.0.7 on 2018-09-24 09:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0007_auto_20180921_1348'),
    ]

    operations = [
        migrations.RenameField(
            model_name='featurecollection',
            old_name='geo_collection',
            new_name='geometry_collection',
        ),
    ]
