# Generated by Django 2.0.7 on 2018-09-24 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0008_auto_20180924_0918'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='deleted',
            field=models.DateTimeField(editable=False, null=True),
        ),
    ]
