# Generated by Django 2.0.7 on 2019-09-30 12:54

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion
import rescape_region.models.resource


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0009_auto_20190930_1247'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('data', django.contrib.postgres.fields.jsonb.JSONField(default=rescape_region.models.resource.default)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='resources', to='rescape_region.Region')),
            ],
        ),
    ]
