# Generated by Django 2.0.7 on 2018-09-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0009_region_deleted'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Feature',
        )
    ]
