# Generated by Django 2.0.7 on 2019-09-30 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0010_resource'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='key',
            field=models.CharField(default='<function now at 0x10f26d378>', max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
