# Generated by Django 3.0.5 on 2020-04-15 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0013_auto_20200324_1214'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RegionLocation',
            new_name='Location',
        ),
    ]
