# Generated by Django 3.0.5 on 2020-06-18 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0015_auto_20200611_1139'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='region',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='region',
            name='updated_at',
        ),
    ]
