# Generated by Django 3.0.8 on 2020-08-03 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0019_auto_20200731_1404'),
    ]

    operations = [
        migrations.AlterField(
            model_name='region',
            name='key',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(fields=('deleted', 'key'), name='unique_region_with_deleted'),
        ),
        migrations.AddConstraint(
            model_name='region',
            constraint=models.UniqueConstraint(condition=models.Q(deleted=None), fields=('key',), name='unique_region_without_deleted'),
        ),
    ]
