# Generated by Django 3.1 on 2020-09-09 09:51

from django.db import migrations, models
import rescape_region.model_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0022_auto_20200902_1044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='data',
            field=models.JSONField(default=rescape_region.model_helpers.region_data_default),
        ),
        migrations.AlterField(
            model_name='location',
            name='geojson',
            field=models.JSONField(default=rescape_region.model_helpers.feature_collection_default),
        ),
        migrations.AlterField(
            model_name='project',
            name='data',
            field=models.JSONField(default=rescape_region.model_helpers.project_data_default),
        ),
        migrations.AlterField(
            model_name='project',
            name='geojson',
            field=models.JSONField(default=rescape_region.model_helpers.feature_collection_default),
        ),
        migrations.AlterField(
            model_name='region',
            name='data',
            field=models.JSONField(default=rescape_region.model_helpers.region_data_default),
        ),
        migrations.AlterField(
            model_name='region',
            name='geojson',
            field=models.JSONField(default=rescape_region.model_helpers.feature_collection_default),
        ),
    ]
