# Generated by Django 3.1.4 on 2020-12-07 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0023_auto_20200909_0951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='key',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
