# Generated by Django 3.2 on 2021-04-28 09:01

from django.db import migrations, models
import rescape_region.model_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0024_auto_20201207_1751'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='data',
            field=models.JSONField(default=rescape_region.model_helpers.settings_data_default),
        ),
    ]
