# Generated by Django 3.2 on 2021-04-28 09:29

from django.db import migrations, models
import rescape_region.models.search_location


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0026_searchlocation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlocation',
            name='data',
            field=models.JSONField(default=rescape_region.models.search_location.data_default),
        ),
        migrations.AlterField(
            model_name='searchlocation',
            name='geojson',
            field=models.JSONField(default=rescape_region.models.search_location.geojson_default),
        ),
    ]
