# Generated by Django 3.2 on 2021-05-02 11:44

from django.db import migrations, models
import rescape_region.models.search_location


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0027_auto_20210428_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlocation',
            name='data',
            field=models.JSONField(default=rescape_region.models.search_location.data_default, null=True),
        ),
        migrations.AlterField(
            model_name='searchlocation',
            name='geojson',
            field=models.JSONField(default=rescape_region.models.search_location.geojson_default, null=True),
        ),
        migrations.AlterField(
            model_name='searchlocation',
            name='identification',
            field=models.JSONField(default=rescape_region.models.search_location.default_search_identification, null=True),
        ),
        migrations.AlterField(
            model_name='searchlocation',
            name='street',
            field=models.JSONField(default=rescape_region.models.search_location.default_search_street, null=True),
        ),
    ]
