# Generated by Django 3.2 on 2021-05-03 08:10

from django.db import migrations, models
import rescape_region.models.jurisdiction


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0028_auto_20210502_1144'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('data', models.JSONField(default=rescape_region.models.jurisdiction.default_jurisdiction_data)),
                ('geojson', models.JSONField(blank=True, null=True)),
            ],
        ),
    ]
