# Generated by Django 3.2 on 2021-05-03 08:19

from django.db import migrations, models
import rescape_region.models.search_jurisdiction


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0029_jurisdiction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchJurisdiction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted', models.DateTimeField(editable=False, null=True)),
                ('identification', models.JSONField(default=rescape_region.models.search_jurisdiction.default_search_identification, null=True)),
                ('data', models.JSONField(default=rescape_region.models.search_jurisdiction.default_search_jursidiction_data, null=True)),
                ('geojson', models.JSONField(default=rescape_region.models.search_jurisdiction.default_geojson, null=True)),
            ],
        ),
    ]
