# Generated by Django 3.2 on 2021-05-03 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0030_searchjurisdiction'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlocation',
            name='jurisdictions',
            field=models.ManyToManyField(to='rescape_region.SearchJurisdiction'),
        ),
    ]
