# Generated by Django 3.2 on 2021-05-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0031_searchlocation_jurisdictions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchlocation',
            name='jurisdictions',
            field=models.ManyToManyField(related_name='rescape_region_jurisdictions', to='rescape_region.SearchJurisdiction'),
        ),
    ]
