# Generated by Django 3.2 on 2021-05-07 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0032_alter_searchlocation_jurisdictions'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchlocation',
            name='name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
