# Generated by Django 3.2 on 2021-06-10 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rescape_region', '0033_searchlocation_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='locations',
            field=models.ManyToManyField(blank=True, related_name='projects', to='rescape_region.Location'),
        ),
    ]
